name : Build and Package Installer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout/@v3

      - name: Set up .Net
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: '8.0.x'

      - name: Restore dependencies
        runs: dotnet Restore

      - name: Build application
        run: dotnet build --configuration Release

      - name: Buld installer (MSBuild)
        run: | 
            nuget restore InventoryManagementSystem.sln
            msbuild InventoryManagementSystem.vdproj /p:Configuration=Release
        shell: cmd

      - name: Upload installer artifact
        uses: actions/upload-artifact@v3
        with:
          name: Installer
          path: |
            **/*.msi
            **/Setup.exe